local M = {}

function M.apply(p)
  local hi = function(group, def)
    vim.api.nvim_set_hl(0, group, def)
  end

  local link = function(from, to)
    vim.api.nvim_set_hl(0, from, { link = to })
  end

  -- editor base
  hi('Normal',         { fg = p.fg, bg = p.bg })
  hi('NormalNC',       { fg = p.fg, bg = p.bg })
  hi('NormalFloat',    { fg = p.fg, bg = p.bg_float })
  hi('FloatBorder',    { fg = p.bg_border, bg = p.bg_float })
  hi('FloatTitle',     { fg = p.amber, bg = p.bg_float, bold = true })
  hi('FloatFooter',    { fg = p.fg_muted, bg = p.bg_float })
  hi('WinSeparator',   { fg = p.bg_border, bg = p.bg })
  hi('VertSplit',      { fg = p.bg_border, bg = p.bg })
  hi('MsgSeparator',   { fg = p.bg_border, bg = p.bg_dim })
  hi('EndOfBuffer',    { fg = p.bg, bg = p.bg })
  hi('SignColumn',     { fg = p.fg_muted, bg = p.bg })
  hi('FoldColumn',     { fg = p.fg_muted, bg = p.bg })
  hi('Folded',         { fg = p.fg_dim, bg = p.bg_dim })
  hi('LineNr',         { fg = p.fg_muted, bg = p.bg })
  hi('LineNrAbove',    { fg = p.fg_muted, bg = p.bg })
  hi('LineNrBelow',    { fg = p.fg_muted, bg = p.bg })
  hi('CursorLine',     { bg = p.bg_cline })
  hi('CursorColumn',   { bg = p.bg_cline })
  hi('CursorLineNr',   { fg = p.amber, bg = p.bg_cline, bold = true })
  hi('CursorLineFold', { fg = p.amber, bg = p.bg_cline })
  hi('CursorLineSign', { fg = p.amber, bg = p.bg_cline })
  hi('ColorColumn',    { bg = p.bg_dim })
  hi('Cursor',         { reverse = true })
  hi('lCursor',        { reverse = true })
  hi('CursorIM',       { reverse = true })
  hi('TermCursor',     { reverse = true })
  hi('MatchParen',     { fg = p.amber, bold = true, underline = true })
  hi('NonText',        { fg = p.fg_muted })
  hi('Whitespace',     { fg = p.bg_border })
  hi('SpecialKey',     { fg = p.blue })
  hi('Conceal',        { fg = p.fg_muted })
  hi('Directory',      { fg = p.blue })
  hi('Title',          { fg = p.amber, bold = true })

  -- visual / search
  hi('Visual',         { bg = p.bg_visual })
  hi('VisualNOS',      { bg = p.bg_visual })
  hi('Search',         { fg = p.bg, bg = p.yellow })
  hi('IncSearch',      { fg = p.bg, bg = p.peach, bold = true })
  hi('CurSearch',      { fg = p.bg, bg = p.peach, bold = true })
  hi('Substitute',     { fg = p.bg, bg = p.peach })
  hi('QuickFixLine',   { bg = p.bg_hl })

  -- popup menu / wildmenu
  hi('Pmenu',          { fg = p.fg, bg = p.bg_float })
  hi('PmenuSel',       { fg = p.fg, bg = p.bg_hl, bold = true })
  hi('PmenuKind',      { fg = p.violet, bg = p.bg_float })
  hi('PmenuKindSel',   { fg = p.violet, bg = p.bg_hl, bold = true })
  hi('PmenuExtra',     { fg = p.fg_muted, bg = p.bg_float })
  hi('PmenuExtraSel',  { fg = p.fg_muted, bg = p.bg_hl })
  hi('PmenuSbar',      { bg = p.bg_dim })
  hi('PmenuThumb',     { bg = p.bg_border })
  hi('PmenuMatch',     { fg = p.amber, bg = p.bg_float, bold = true })
  hi('PmenuMatchSel',  { fg = p.amber, bg = p.bg_hl, bold = true })
  hi('WildMenu',       { fg = p.fg, bg = p.bg_hl })
  hi('ComplMatchIns',  { fg = p.amber, bold = true })

  -- statusline / tabline / winbar
  hi('StatusLine',     { fg = p.fg, bg = p.bg_float })
  hi('StatusLineNC',   { fg = p.fg_muted, bg = p.bg_dim })
  hi('TabLine',        { fg = p.fg_muted, bg = p.bg_dim })
  hi('TabLineFill',    { fg = p.fg_muted, bg = p.bg_dim })
  hi('TabLineSel',     { fg = p.fg, bg = p.bg, bold = true })
  hi('WinBar',         { fg = p.fg, bg = p.bg })
  hi('WinBarNC',       { fg = p.fg_muted, bg = p.bg })

  -- messages
  hi('ModeMsg',        { fg = p.fg, bold = true })
  hi('MoreMsg',        { fg = p.green })
  hi('MsgArea',        { fg = p.fg })
  hi('Question',       { fg = p.green })
  hi('ErrorMsg',       { fg = p.red, bold = true })
  hi('WarningMsg',     { fg = p.yellow })

  -- spell
  hi('SpellBad',       { sp = p.red, undercurl = true })
  hi('SpellCap',       { sp = p.yellow, undercurl = true })
  hi('SpellLocal',     { sp = p.blue, undercurl = true })
  hi('SpellRare',      { sp = p.violet, undercurl = true })

  -- diff
  hi('DiffAdd',        { bg = p.diff_add })
  hi('DiffChange',     { bg = p.diff_change })
  hi('DiffDelete',     { fg = p.red, bg = p.diff_delete })
  hi('DiffText',       { bg = p.diff_text, bold = true })
  hi('Added',          { fg = p.green })
  hi('Changed',        { fg = p.yellow })
  hi('Removed',        { fg = p.red })

  -- diagnostics
  hi('DiagnosticError',                 { fg = p.red })
  hi('DiagnosticWarn',                  { fg = p.yellow })
  hi('DiagnosticInfo',                  { fg = p.blue_dim })
  hi('DiagnosticHint',                  { fg = p.green_dim })
  hi('DiagnosticOk',                    { fg = p.green })
  hi('DiagnosticVirtualTextError',      { fg = p.red })
  hi('DiagnosticVirtualTextWarn',       { fg = p.yellow })
  hi('DiagnosticVirtualTextInfo',       { fg = p.blue_dim })
  hi('DiagnosticVirtualTextHint',       { fg = p.green_dim })
  hi('DiagnosticUnderlineError',        { sp = p.red, undercurl = true })
  hi('DiagnosticUnderlineWarn',         { sp = p.yellow, undercurl = true })
  hi('DiagnosticUnderlineInfo',         { sp = p.blue_dim, undercurl = true })
  hi('DiagnosticUnderlineHint',         { sp = p.green_dim, undercurl = true })
  hi('DiagnosticUnnecessary',           { fg = p.fg_muted })
  hi('DiagnosticDeprecated',            { fg = p.fg_muted, strikethrough = true })

  -- lsp references / hints
  hi('LspReferenceText',                { bg = p.bg_hl })
  hi('LspReferenceRead',                { bg = p.bg_hl })
  hi('LspReferenceWrite',               { bg = p.bg_hl, bold = true })
  hi('LspInlayHint',                    { fg = p.fg_muted, bg = p.bg_dim, italic = true })
  hi('LspCodeLens',                     { fg = p.fg_muted, italic = true })
  hi('LspCodeLensSeparator',            { fg = p.fg_muted })
  hi('LspSignatureActiveParameter',     { fg = p.amber, bold = true })

  -- standard syntax
  hi('Comment',        { fg = p.comment, italic = true })
  hi('Constant',       { fg = p.peach })
  hi('String',         { fg = p.green })
  hi('Character',      { fg = p.green })
  hi('Number',         { fg = p.peach })
  hi('Float',          { fg = p.peach })
  hi('Boolean',        { fg = p.peach })
  hi('Identifier',     { fg = p.fg })
  hi('Function',       { fg = p.amber })
  hi('Statement',      { fg = p.violet })
  hi('Conditional',    { fg = p.violet })
  hi('Repeat',         { fg = p.violet })
  hi('Label',          { fg = p.violet })
  hi('Operator',       { fg = p.orange })
  hi('Keyword',        { fg = p.violet })
  hi('Exception',      { fg = p.red, italic = true })
  hi('PreProc',        { fg = p.pink })
  hi('Include',        { fg = p.pink })
  hi('Define',         { fg = p.pink })
  hi('Macro',          { fg = p.pink })
  hi('PreCondit',      { fg = p.pink })
  hi('Type',           { fg = p.blue })
  hi('StorageClass',   { fg = p.violet })
  hi('Structure',      { fg = p.blue })
  hi('Typedef',        { fg = p.blue })
  hi('Special',        { fg = p.peach })
  hi('SpecialChar',    { fg = p.peach })
  hi('Tag',            { fg = p.blue })
  hi('Delimiter',      { fg = p.fg_dim })
  hi('SpecialComment', { fg = p.comment, bold = true, italic = true })
  hi('Debug',          { fg = p.red })
  hi('Underlined',     { underline = true })
  hi('Error',          { fg = p.red, bold = true })
  hi('Todo',           { fg = p.bg, bg = p.amber, bold = true })

  -- treesitter
  hi('@variable',                  { fg = p.fg })
  hi('@variable.builtin',          { fg = p.red, italic = true })
  hi('@variable.parameter',        { fg = p.fg_dim, italic = true })
  hi('@variable.member',           { fg = p.blue_dim })
  hi('@constant',                  { fg = p.peach })
  hi('@constant.builtin',          { fg = p.peach, italic = true })
  hi('@constant.macro',            { fg = p.pink })
  hi('@module',                    { fg = p.blue })
  hi('@module.builtin',            { fg = p.blue, italic = true })
  hi('@label',                     { fg = p.violet })
  hi('@string',                    { fg = p.green })
  hi('@string.escape',             { fg = p.peach })
  hi('@string.regexp',             { fg = p.peach })
  hi('@string.special',            { fg = p.peach })
  hi('@string.special.url',        { fg = p.blue, underline = true })
  hi('@character',                 { fg = p.green })
  hi('@character.special',         { fg = p.peach })
  hi('@boolean',                   { fg = p.peach })
  hi('@number',                    { fg = p.peach })
  hi('@number.float',              { fg = p.peach })
  hi('@type',                      { fg = p.blue })
  hi('@type.builtin',              { fg = p.blue, italic = true })
  hi('@type.definition',           { fg = p.blue })
  hi('@attribute',                 { fg = p.amber })
  hi('@attribute.builtin',         { fg = p.amber, italic = true })
  hi('@property',                  { fg = p.blue_dim })
  hi('@function',                  { fg = p.amber })
  hi('@function.builtin',          { fg = p.amber, italic = true })
  hi('@function.call',             { fg = p.amber })
  hi('@function.macro',            { fg = p.pink })
  hi('@function.method',           { fg = p.amber })
  hi('@function.method.call',      { fg = p.amber })
  hi('@constructor',               { fg = p.blue })
  hi('@operator',                  { fg = p.orange })
  hi('@keyword',                   { fg = p.violet })
  hi('@keyword.function',          { fg = p.violet, italic = true })
  hi('@keyword.coroutine',         { fg = p.violet })
  hi('@keyword.operator',          { fg = p.violet })
  hi('@keyword.import',            { fg = p.pink })
  hi('@keyword.type',              { fg = p.violet, italic = true })
  hi('@keyword.modifier',          { fg = p.violet })
  hi('@keyword.repeat',            { fg = p.violet })
  hi('@keyword.return',            { fg = p.pink })
  hi('@keyword.debug',             { fg = p.red })
  hi('@keyword.exception',         { fg = p.red, italic = true })
  hi('@keyword.conditional',       { fg = p.violet })
  hi('@keyword.conditional.ternary', { fg = p.orange })
  hi('@keyword.directive',         { fg = p.pink })
  hi('@keyword.directive.define',  { fg = p.pink })
  hi('@punctuation.delimiter',     { fg = p.fg_dim })
  hi('@punctuation.bracket',       { fg = p.fg_dim })
  hi('@punctuation.special',       { fg = p.peach })
  hi('@comment',                   { fg = p.comment, italic = true })
  hi('@comment.documentation',     { fg = p.comment, italic = true })
  hi('@comment.error',             { fg = p.red, bold = true })
  hi('@comment.warning',           { fg = p.yellow, bold = true })
  hi('@comment.todo',              { fg = p.bg, bg = p.amber, bold = true })
  hi('@comment.note',              { fg = p.bg, bg = p.green_dim, bold = true })
  hi('@tag',                       { fg = p.violet })
  hi('@tag.builtin',               { fg = p.violet, italic = true })
  hi('@tag.attribute',             { fg = p.amber, italic = true })
  hi('@tag.delimiter',             { fg = p.fg_dim })

  -- markup (markdown / help)
  hi('@markup',                    { fg = p.fg })
  hi('@markup.strong',             { fg = p.peach, bold = true })
  hi('@markup.italic',             { fg = p.green, italic = true })
  hi('@markup.strikethrough',      { fg = p.fg_muted, strikethrough = true })
  hi('@markup.underline',          { underline = true })
  hi('@markup.heading',            { fg = p.amber, bold = true })
  hi('@markup.heading.1',          { fg = p.amber, bold = true })
  hi('@markup.heading.2',          { fg = p.peach, bold = true })
  hi('@markup.heading.3',          { fg = p.violet, bold = true })
  hi('@markup.heading.4',          { fg = p.blue, bold = true })
  hi('@markup.heading.5',          { fg = p.green, bold = true })
  hi('@markup.heading.6',          { fg = p.blue_dim, bold = true })
  hi('@markup.heading.marker',     { fg = p.orange, bold = true })
  hi('@markup.quote',              { fg = p.fg_dim, italic = true })
  hi('@markup.math',               { fg = p.blue })
  hi('@markup.link',               { fg = p.blue })
  hi('@markup.link.label',         { fg = p.violet })
  hi('@markup.link.url',           { fg = p.blue, underline = true })
  hi('@markup.raw',                { fg = p.green })
  hi('@markup.raw.block',          { fg = p.green, bg = p.bg_dim })
  hi('@markup.list',               { fg = p.peach })
  hi('@markup.list.checked',       { fg = p.green_dim })
  hi('@markup.list.unchecked',     { fg = p.fg_muted })

  -- diff treesitter
  hi('@diff.plus',                 { fg = p.green, bg = p.diff_add })
  hi('@diff.minus',                { fg = p.red, bg = p.diff_delete })
  hi('@diff.delta',                { fg = p.yellow, bg = p.diff_change })

  -- gitsigns
  hi('GitSignsAdd',                { fg = p.green })
  hi('GitSignsChange',             { fg = p.yellow })
  hi('GitSignsDelete',             { fg = p.red })
  hi('GitSignsAddNr',              { fg = p.green })
  hi('GitSignsChangeNr',           { fg = p.yellow })
  hi('GitSignsDeleteNr',           { fg = p.red })
  hi('GitSignsCurrentLineBlame',   { fg = p.fg_muted, italic = true })

  -- snacks (picker / dashboard / notifier)
  link('SnacksNormal',             'NormalFloat')
  link('SnacksNormalNC',           'NormalFloat')
  link('SnacksWinBar',             'FloatTitle')
  link('SnacksBackdrop',           'NormalFloat')
  hi('SnacksPickerDir',            { fg = p.fg_muted })
  hi('SnacksPickerMatch',          { fg = p.amber, bold = true })
  hi('SnacksPickerSelected',       { fg = p.amber })
  hi('SnacksPickerPrompt',         { fg = p.violet, bold = true })
  hi('SnacksDashboardHeader',      { fg = p.amber, bold = true })
  hi('SnacksDashboardIcon',        { fg = p.violet })
  hi('SnacksDashboardKey',         { fg = p.peach })
  hi('SnacksDashboardDesc',        { fg = p.fg })
  hi('SnacksDashboardFooter',      { fg = p.fg_muted, italic = true })
  hi('SnacksDashboardSpecial',     { fg = p.green })
  hi('SnacksNotifierInfo',         { fg = p.blue_dim })
  hi('SnacksNotifierWarn',         { fg = p.yellow })
  hi('SnacksNotifierError',        { fg = p.red })
  hi('SnacksNotifierDebug',        { fg = p.violet })
  hi('SnacksNotifierTrace',        { fg = p.fg_muted })

  -- flash
  hi('FlashLabel',                 { fg = p.bg, bg = p.amber, bold = true })
  hi('FlashMatch',                 { fg = p.bg, bg = p.peach })
  hi('FlashCurrent',               { fg = p.bg, bg = p.yellow, bold = true })

  -- treesitter context
  hi('TreesitterContext',           { bg = p.bg_dim })
  hi('TreesitterContextLineNumber', { fg = p.amber, bg = p.bg_dim, bold = true })
  hi('TreesitterContextBottom',     { sp = p.bg_border, underline = true })

  -- diffview
  link('DiffviewNormal',           'Normal')
  link('DiffviewFilePanelTitle',   'Title')
  hi('DiffviewFilePanelCounter',   { fg = p.amber, bold = true })
  hi('DiffviewFilePanelFileName',  { fg = p.fg })
  hi('DiffviewFilePanelPath',      { fg = p.fg_muted })
  hi('DiffviewFolderName',         { fg = p.blue })
  hi('DiffviewFolderSign',         { fg = p.fg_muted })
  hi('DiffviewStatusAdded',        { fg = p.green })
  hi('DiffviewStatusModified',     { fg = p.yellow })
  hi('DiffviewStatusDeleted',      { fg = p.red })
  hi('DiffviewStatusRenamed',      { fg = p.violet })
  hi('DiffviewStatusUntracked',    { fg = p.peach })

  -- oil
  hi('OilDir',                     { fg = p.blue })
  hi('OilDirIcon',                 { fg = p.blue })
  hi('OilFile',                    { fg = p.fg })
  hi('OilLink',                    { fg = p.violet })
  hi('OilLinkTarget',              { fg = p.violet, italic = true })
  hi('OilSocket',                  { fg = p.peach })

  -- terminal palette (16 colors)
  vim.g.terminal_color_0  = p.bg_dim
  vim.g.terminal_color_1  = p.red
  vim.g.terminal_color_2  = p.green
  vim.g.terminal_color_3  = p.yellow
  vim.g.terminal_color_4  = p.blue
  vim.g.terminal_color_5  = p.violet
  vim.g.terminal_color_6  = p.green_dim
  vim.g.terminal_color_7  = p.fg_dim
  vim.g.terminal_color_8  = p.fg_muted
  vim.g.terminal_color_9  = p.peach
  vim.g.terminal_color_10 = p.green
  vim.g.terminal_color_11 = p.amber
  vim.g.terminal_color_12 = p.blue_dim
  vim.g.terminal_color_13 = p.pink
  vim.g.terminal_color_14 = p.green_dim
  vim.g.terminal_color_15 = p.fg
end

return M
